CREATE TABLE IF NOT EXISTS `recurring_invoice` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`client_id` text NOT NULL,
	`project_id` text,
	`service_id` text,
	`name` text NOT NULL,
	`amount` integer NOT NULL,
	`tax_rate` integer DEFAULT 1900 NOT NULL,
	`currency` text DEFAULT 'RON' NOT NULL,
	`recurring_type` text NOT NULL,
	`recurring_interval` integer DEFAULT 1 NOT NULL,
	`start_date` timestamp NOT NULL,
	`end_date` timestamp,
	`next_run_date` timestamp NOT NULL,
	`last_run_date` timestamp,
	`issue_date_offset` integer DEFAULT 0 NOT NULL,
	`due_date_offset` integer DEFAULT 30 NOT NULL,
	`notes` text,
	`is_active` number DEFAULT true NOT NULL,
	`created_by_user_id` text NOT NULL,
	`created_at` timestamp DEFAULT current_date NOT NULL,
	`updated_at` timestamp DEFAULT current_date NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`client_id`) REFERENCES `client`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`project_id`) REFERENCES `project`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`service_id`) REFERENCES `service`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by_user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
