CREATE TABLE `hosting_account` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`client_id` text NOT NULL,
	`da_server_id` text NOT NULL,
	`da_package_id` text,
	`hosting_product_id` text,
	`da_username` text NOT NULL,
	`domain` text NOT NULL,
	`status` text DEFAULT 'pending' NOT NULL,
	`suspend_reason` text,
	`da_credentials_encrypted` text,
	`disk_usage` integer,
	`bandwidth_usage` integer,
	`email_count` integer,
	`db_count` integer,
	`inode_count` integer,
	`next_due_date` text,
	`recurring_amount` integer DEFAULT 0 NOT NULL,
	`currency` text DEFAULT 'RON' NOT NULL,
	`notes` text,
	`whmcs_service_id` integer,
	`last_synced_at` text,
	`created_at` text DEFAULT (current_timestamp) NOT NULL,
	`updated_at` text DEFAULT (current_timestamp) NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`client_id`) REFERENCES `client`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`da_server_id`) REFERENCES `da_server`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`da_package_id`) REFERENCES `da_package`(`id`) ON UPDATE no action ON DELETE set null,
	FOREIGN KEY (`hosting_product_id`) REFERENCES `hosting_product`(`id`) ON UPDATE no action ON DELETE set null
);
