CREATE TABLE IF NOT EXISTS `content_article` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`brand` text DEFAULT 'unknown' NOT NULL,
	`source_url` text NOT NULL,
	`source_domain` text NOT NULL,
	`title` text,
	`slug` text,
	`excerpt` text,
	`body_html` text,
	`body_text` text,
	`word_count` integer DEFAULT 0 NOT NULL,
	`featured_image_url` text,
	`images` text,
	`published_at` timestamp,
	`extract_status` text DEFAULT 'pending' NOT NULL,
	`extract_error` text,
	`used_puppeteer` number DEFAULT false NOT NULL,
	`extracted_at` timestamp,
	`rewrite_status` text DEFAULT 'none' NOT NULL,
	`target_wp_site_id` text,
	`wp_post_id` integer,
	`scheduled_at` timestamp,
	`created_at` timestamp DEFAULT current_timestamp NOT NULL,
	`updated_at` timestamp DEFAULT current_timestamp NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`) ON UPDATE no action ON DELETE no action
);
