CREATE TABLE IF NOT EXISTS `website_content_profile` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`website_id` text NOT NULL,
	`tone` text,
	`audience` text,
	`language` text DEFAULT 'ro' NOT NULL,
	`keywords` text,
	`topics` text,
	`do_list` text,
	`dont_list` text,
	`guardrails` text,
	`sample_urls` text,
	`extra_notes` text,
	`publish_mode` text DEFAULT 'manual' NOT NULL,
	`cadence_per_week` integer DEFAULT 3 NOT NULL,
	`days_of_week` text,
	`publish_time` text DEFAULT '10:00' NOT NULL,
	`default_wp_status` text DEFAULT 'draft' NOT NULL,
	`auto_approve` number DEFAULT false NOT NULL,
	`created_at` timestamp DEFAULT current_timestamp NOT NULL,
	`updated_at` timestamp DEFAULT current_timestamp NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`),
	FOREIGN KEY (`website_id`) REFERENCES `client_website`(`id`)
);
