CREATE TABLE `service_hours_order` (
	`id` text PRIMARY KEY NOT NULL,
	`tenant_id` text NOT NULL,
	`client_id` text,
	`rate_slug` text NOT NULL,
	`rate_label` text NOT NULL,
	`rate_eur` integer NOT NULL,
	`hours` integer NOT NULL,
	`net_cents` integer NOT NULL,
	`vat_cents` integer NOT NULL,
	`gross_cents` integer NOT NULL,
	`vat_percent` integer NOT NULL,
	`currency` text DEFAULT 'EUR' NOT NULL,
	`billing_type` text DEFAULT 'company' NOT NULL,
	`contact_name` text NOT NULL,
	`contact_email` text NOT NULL,
	`contact_phone` text,
	`company_name` text,
	`cui` text,
	`note` text,
	`status` text DEFAULT 'pending_payment' NOT NULL,
	`stripe_payment_intent_id` text,
	`invoice_id` text,
	`ip_address` text,
	`user_agent` text,
	`paid_at` timestamp,
	`created_at` timestamp DEFAULT current_timestamp NOT NULL,
	`updated_at` timestamp DEFAULT current_timestamp NOT NULL,
	FOREIGN KEY (`tenant_id`) REFERENCES `tenant`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`client_id`) REFERENCES `client`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`invoice_id`) REFERENCES `invoice`(`id`) ON UPDATE no action ON DELETE no action
);
