CREATE TABLE `pagespeed_measurement` (
	`id` text PRIMARY KEY NOT NULL,
	`site_id` text NOT NULL,
	`strategy` text NOT NULL,
	`measured_at` timestamp NOT NULL,
	`week_key` text NOT NULL,
	`status` text DEFAULT 'ok' NOT NULL,
	`error_message` text,
	`performance` integer,
	`accessibility` integer,
	`best_practices` integer,
	`seo` integer,
	`lcp_ms` integer,
	`cls` real,
	`tbt_ms` integer,
	`fcp_ms` integer,
	`speed_index_ms` integer,
	`inp_ms` integer,
	`ttfb_ms` integer,
	`total_bytes` integer,
	`request_count` integer,
	`field_lcp_ms` integer,
	`field_inp_ms` integer,
	`field_cls` real,
	`field_sample_count` integer,
	`opportunities` text,
	`created_at` timestamp DEFAULT current_timestamp NOT NULL,
	FOREIGN KEY (`site_id`) REFERENCES `pagespeed_site`(`id`) ON UPDATE no action ON DELETE cascade
);
