/**
 * Explicațiile scurte de lângă fiecare rând din tabelele de comparație
 * (`FeatureHint`, tooltip la hover/focus). Cheia = `Feature.id` din `ots-catalog.ts`.
 *
 * Stau separat de catalog ca să nu-l umfle și pentru că NU conțin prețuri: pot fi
 * importate și din componentele paginii publice fără să ocolească poarta cu parolă.
 */

export const FEATURE_HINTS: Record<string, string> = {
	'dashboard-realtime': 'Vezi în CRM, oricând, cheltuiala, afișările, clicurile și conversiile campaniilor, actualizate automat din platforme, fără să aștepți raportul lunar.',
	'history-30': 'Datele campaniilor din ultimele 30 de zile rămân accesibile în CRM, ca să compari săptămânile între ele și să vezi efectul optimizărilor recente.',
	'history-full': 'Păstrăm datele pe toată durata colaborării, ca să poți compara perioade, sezoane și ani între ele și să vezi evoluția pe termen lung.',
	'export-reports': 'Orice raport din CRM poate fi descărcat ca PDF sau Excel, util pentru contabilitate, ședințe interne sau analize proprii în afara platformei.',
	'custom-kpi': 'Definim împreună indicatorii care contează pentru afacerea ta (cost per lead, valoare per comandă etc.) și îi urmărim în rapoarte construite pentru ei.',
	'alerts': 'Ești anunțat pe e-mail și în CRM când apare ceva neobișnuit: buget epuizat, campanie oprită, scădere bruscă a conversiilor. Afli la timp, nu la raportul următor.',
	'team-users': 'Numărul de conturi de acces în CRM pentru oamenii din firma ta (asociat, contabil, coleg de marketing), fiecare cu propriul login și propriile notificări.',
	'custom-integrations': 'Conectăm CRM-ul cu sistemele pe care le folosești deja (CRM intern, Slack, WhatsApp), ca lead-urile și alertele să ajungă direct acolo unde lucrează echipa ta.',
	'bi-api': 'Acces programatic la datele campaniilor, ca echipa ta să le combine cu vânzările sau stocurile în Looker, Power BI sau alte instrumente de analiză.',
	'gads-1': 'Stabilim de la început ce urmărim (apeluri, comenzi, formulare), bugetul și publicul țintă, ca fiecare campanie să aibă un scop măsurabil.',
	'gads-2': 'Instalăm măsurarea acțiunilor importante de pe site (comandă, formular, apel) prin GTM, GA4 și Google Ads, ca să știm exact ce campanie aduce rezultate.',
	'gads-3': 'Construim campaniile de la zero: structură, cuvinte-cheie, anunțuri, extensii și setări de public țintă, pe baza obiectivelor și a analizei site-ului tău.',
	'gads-4': 'Verificăm regulat campaniile și ajustăm licitațiile, cuvintele-cheie, anunțurile și bugetele, ca banii să meargă spre ce aduce rezultate.',
	'gads-5': 'Analizăm site-ul și paginile pe care ajung vizitatorii din reclame (viteză, claritate, formulare): o pagină slabă irosește bugetul oricât de bune ar fi anunțurile.',
	'gads-6': 'Canalul prin care ne poți contacta pentru întrebări despre campanii. Pe e-mail răspundem în scris; la telefon lămurim rapid situațiile urgente.',
	'gads-7': 'La final de lună primești în CRM un raport cu rezultatele, costurile și concluziile perioadei, plus ce urmează să facem luna următoare.',
	'gads-8': 'Raport în CRM în fiecare săptămână, ca să vezi din timp ce funcționează și să putem corecta din mers, fără să așteptăm finalul lunii.',
	'gads-9': 'Rapoarte construite după nevoile tale: pe produs, locație, campanie sau orice altă împărțire care contează pentru deciziile din afacere.',
	'gads-10': 'Nu primești doar cifre: discutăm împreună ce înseamnă rezultatele, ce decizii de buget sau ofertă decurg din ele și ce testăm în perioada următoare.',
	'gads-11': 'Echipa noastră creează bannerele grafice pentru campaniile Display, YouTube și Performance Max, în formatele cerute de Google, fără să ai nevoie de designer propriu.',
	'gads-12': 'Sesiuni de consultanță dincolo de Google Ads: cum se leagă reclamele de site, oferte, SEO și rețele sociale, ca să ai o direcție de marketing coerentă.',
	'gads-13': 'Configurăm și întreținem contul Google Merchant Center (feed de produse, aprobări, erori), baza campaniilor Shopping și Performance Max pentru magazine online.',
	'gads-14': 'Numărul de audiențe segmentate create și întreținute lunar: liste de vizitatori, clienți sau utilizatori cu interese specifice, folosite pentru remarketing și țintire.',
	'gads-15': 'Formatele de bază: anunțuri text în căutările Google, bannere pe site-uri partenere, promovare locală și remarketing către cei care ți-au vizitat deja site-ul.',
	'gads-16': 'Performance Max e tipul de campanie care afișează reclamele tale automat pe toate canalele Google (căutare, YouTube, Gmail, Maps), optimizat de algoritm pe conversii.',
	'gads-17': 'Reclame video pe YouTube și anunțuri vizuale în Discover și Gmail, utile pentru notorietate și pentru a ajunge la clienți înainte să caute activ produsul.',
	'gads-18': 'Numărul de linii de produse sau servicii pe care le promovăm cu campanii separate. Fiecare categorie cere cuvinte-cheie, anunțuri și bugete proprii.',
	'gads-19': 'Întâlnire video săptămânală cu specialistul tău, în care trecem prin rezultate, răspundem la întrebări și stabilim prioritățile pentru săptămâna următoare.',
	'gads-20': 'Formulare de contact direct în anunțurile Google; datele completate de client ajung automat pe e-mailul tău, ca să îl poți suna cât e încă interesat.',
	'gads-21': 'Datele de conversie ajung la Google direct de pe server, securizat, așa că măsurarea rămâne completă și când vizitatorul are blocator de reclame sau refuză cookie-urile.',
	'gads-22': 'Configurăm Consent Mode v2, mecanismul Google prin care măsurarea respectă alegerea vizitatorilor la bannerul de cookie-uri, cerut pentru conformitate GDPR în UE.',
	'gads-23': 'Urmărim și apelurile telefonice, conversațiile pe WhatsApp și Messenger pornite din reclame, ca să știi câți clienți te sună, pe lângă cei care completează formulare.',
	'gads-24': 'Importăm în Google Ads vânzările finalizate offline sau mai târziu (la telefon, în showroom), ca algoritmul să învețe din clienții reali, nu din simple clicuri.',
	'gads-25': 'Conectăm Google Ads cu CRM-ul tău de vânzări, ca să știm care lead-uri au devenit clienți și să optimizăm campaniile după calitatea lor, nu după numărul de formulare.',
	'meta-1': 'Stabilim de la început ce urmărim (mesaje, comenzi, formulare, vizite), bugetul și publicul țintă, ca fiecare campanie să aibă un scop măsurabil.',
	'meta-2': 'Numărul de obiective distincte pentru care construim câte o strategie proprie (ex. vânzări, mesaje, notorietate). Fiecare obiectiv cere campanii și mesaje diferite.',
	'meta-3': 'Reclamele tale apar în toate plasamentele Meta: feed și Stories pe Facebook și Instagram, conversații în Messenger și listări în Marketplace, dintr-un singur cont.',
	'meta-4': 'Verificăm regulat campaniile și ajustăm audiențele, bugetele și creațiile, oprind ce nu dă rezultate și mutând bugetul spre ce funcționează.',
	'meta-5': 'Numărul de materiale vizuale produse lunar (imagini, carusele, clipuri scurte). Reclamele se uzează repede pe Meta; creațiile noi mențin costurile sub control.',
	'meta-6': 'Numărul de audiențe segmentate create și întreținute lunar: vizitatori ai site-ului, clienți din baza ta, persoane care au interacționat cu pagina sau cu reclamele.',
	'meta-7': 'Meta găsește oameni asemănători cu clienții tăi existenți (după comportament și interese), construind audiențe noi pornind de la cumpărători reali, nu de la presupuneri.',
	'meta-8': 'Scriem textele anunțurilor (titlu, descriere, apel la acțiune) adaptate fiecărui obiectiv și public, testând mai multe variante ca să vedem ce convinge.',
	'meta-9': 'Instalăm Meta Pixel, codul care înregistrează acțiunile de pe site (vizită, adăugare în coș, comandă), ca să putem măsura rezultatele și construi remarketing.',
	'meta-10': 'Trimitem evenimentele de conversie direct de pe server către Meta, pe lângă cele din browser. Măsurarea rămâne completă și pe iOS, cu blocatoare de reclame sau cookie-uri refuzate.',
	'meta-11': 'Conectăm catalogul magazinului la Meta: reclamele afișează automat produsele potrivite fiecărei persoane, inclusiv cele văzute sau abandonate în coș.',
	'meta-12': 'Advantage+ Shopping e campania automatizată Meta pentru magazine online: algoritmul alege publicul, plasamentele și creațiile, optimizând pe vânzări.',
	'meta-13': 'Reclame video verticale în Reels și Stories pe Facebook și Instagram, plasamente cu consum mare pe mobil, adaptate ca format și durată fiecărui canal.',
	'meta-14': 'La final de lună primești în CRM un raport cu rezultatele, costurile și concluziile perioadei, plus ce urmează să facem luna următoare.',
	'meta-15': 'Raport în CRM în fiecare săptămână, ca să vezi din timp ce funcționează și să putem corecta din mers, fără să așteptăm finalul lunii.',
	'meta-16': 'Rulăm în paralel variante diferite de imagine, text sau audiență și păstrăm ce funcționează. Deciziile se iau pe date, nu pe gust personal.',
	'meta-17': 'Canalul prin care ne poți contacta pentru întrebări despre campanii. Pe e-mail răspundem în scris; la telefon lămurim rapid situațiile urgente.',
	'meta-18': 'Sesiuni de consultanță dincolo de Meta Ads: cum se leagă reclamele de site, oferte, Google și conținut organic, ca să ai o direcție de marketing coerentă.',
	'meta-19': 'Întâlnire video săptămânală cu specialistul tău, în care trecem prin rezultate, răspundem la întrebări și stabilim prioritățile pentru săptămâna următoare.',
	'meta-20': 'Formulare de contact direct în Facebook și Instagram, fără ca omul să iasă din aplicație; datele completate ajung automat pe e-mailul tău, ca să îl suni rapid.',
	'meta-21': 'Reclame care deschid o conversație pe WhatsApp Business cu firma ta, plus configurarea contului; util când clienții preferă să întrebe înainte să cumpere.',
	'tt-1': 'Stabilim de la început ce urmărim (vizite, comenzi, formulare, instalări), bugetul și publicul țintă, ca fiecare campanie să aibă un scop măsurabil.',
	'tt-2': 'Numărul de obiective distincte pentru care construim câte o strategie proprie (ex. vânzări, trafic, notorietate). Fiecare obiectiv cere campanii și mesaje diferite.',
	'tt-3': 'Reclamele tale apar în fluxul For You de pe TikTok și în rețeaua de aplicații și site-uri partenere (Pangle), dintr-un singur cont de advertising.',
	'tt-4': 'Verificăm regulat campaniile și ajustăm audiențele, bugetele și creațiile, oprind ce nu dă rezultate și mutând bugetul spre ce funcționează.',
	'tt-5': 'Numărul de clipuri video produse lunar. Pe TikTok conținutul se uzează rapid, iar clipurile noi, în stilul platformei, mențin costurile sub control.',
	'tt-6': 'Numărul de audiențe segmentate create și întreținute lunar: vizitatori ai site-ului, clienți din baza ta, persoane care au interacționat cu clipurile sau cu contul.',
	'tt-7': 'Scriem textele anunțurilor și indicațiile pentru clip (primele secunde, mesaj, apel la acțiune) în stilul platformei, ca reclama să nu pară reclamă.',
	'tt-8': 'Instalăm TikTok Pixel pe site și Events API pe server, ca acțiunile vizitatorilor (vizită, coș, comandă) să fie măsurate complet și folosite la optimizare.',
	'tt-9': 'Te ajutăm să conectezi catalogul de produse la TikTok, ca reclamele să afișeze automat produsele potrivite și să poți rula campanii de tip shopping.',
	'tt-10': 'Spark Ads promovează clipuri publicate deja organic, de pe contul tău sau al unui creator, păstrând reacțiile și comentariile; par mai naturale decât reclamele clasice.',
	'tt-11': 'Te orientăm în colaborările cu creatori TikTok: selecție, instrucțiuni, drepturi de folosire a clipurilor în reclame și configurarea tehnică a parteneriatului.',
	'tt-12': 'La final de lună primești în CRM un raport cu rezultatele, costurile și concluziile perioadei, plus ce urmează să facem luna următoare.',
	'tt-13': 'Raport în CRM în fiecare săptămână, ca să vezi din timp ce funcționează și să putem corecta din mers, fără să așteptăm finalul lunii.',
	'tt-14': 'Testăm în paralel formate creative diferite (primele secunde, durată, stil, muzică) și păstrăm ce funcționează. Deciziile se iau pe date, nu pe gust personal.',
	'tt-15': 'Canalul prin care ne poți contacta pentru întrebări despre campanii. Pe e-mail răspundem în scris; la telefon lămurim rapid situațiile urgente.',
	'tt-16': 'Sesiuni de consultanță dincolo de TikTok Ads: cum se leagă reclamele de site, oferte, alte platforme și conținut organic, ca să ai o direcție de marketing coerentă.',
	'tt-17': 'Întâlnire video săptămânală cu specialistul tău, în care trecem prin rezultate, răspundem la întrebări și stabilim prioritățile pentru săptămâna următoare.',
	'tt-18': 'Formulare de contact direct în TikTok, fără ca omul să iasă din aplicație; datele completate ajung automat pe e-mailul tău, ca să îl suni rapid.',
	'seo-1': 'Verificăm cum sunt organizate paginile, meniurile și adresele URL, ca Google să le parcurgă ușor, iar vizitatorii să găsească rapid ce caută.',
	'seo-2': 'Expresiile de căutare alese împreună cu tine, pentru care optimizăm activ paginile. Mai multe cuvinte cheie înseamnă mai multe tipuri de căutări acoperite.',
	'seo-3': 'Măsurăm autoritatea domeniului (DA) și pozițiile reale în rezultatele Google (SERP), ca să știm de unde pornim și ce progres facem de la o lună la alta.',
	'seo-4': 'Analizăm site-urile care trimit linkuri către al tău și obținem linkuri noi, relevante. Linkurile de calitate sunt un semnal de încredere pentru Google.',
	'seo-5': 'În fiecare săptămână vezi în contul tău din CRM pozițiile cuvintelor cheie urmărite, fără să ceri rapoarte sau să aștepți finalul lunii.',
	'seo-6': 'Numărul de cuvinte cheie pentru care primești lunar evoluția pozițiilor și a traficului, într-un raport ușor de urmărit și de comparat cu luna trecută.',
	'seo-7': 'Conectăm site-ul la instrumentul gratuit Google care arată erorile de indexare, căutările care aduc vizitatori și paginile care au nevoie de atenție.',
	'seo-8': 'Creăm sau optimizăm fișa afacerii din Google Maps și căutare, ca să apari corect când clienții caută firme din zona ta, cu date de contact și recenzii la zi.',
	'seo-9': 'Expresii mai lungi și mai specifice (ex. „reparații centrale termice Cluj”), cu concurență mai mică și vizitatori mai aproape de decizia de a cumpăra.',
	'seo-10': 'Rescriem textele paginilor în jurul subiectului principal și al termenilor înrudiți, ca Google să înțeleagă clar despre ce este fiecare pagină și cui se adresează.',
	'seo-11': 'Setăm nume, dimensiuni și texte alternative corecte pentru imagini și reparăm linkurile interne, pentru pagini mai rapide și mai ușor de înțeles de Google.',
	'seo-12': 'Configurăm fișierul de setări al serverului pentru redirecționări, compresie și reguli de cache, astfel încât site-ul să se încarce corect și fără erori.',
	'seo-13': 'Vedem pentru ce cuvinte apar concurenții, de unde își iau linkurile și ce subiecte nu acoperă încă, ca să țintim oportunitățile pe care ei le ratează.',
	'seo-14': 'Articole sau pagini noi, scrise lunar pe cuvintele cheie vizate. Conținutul nou aduce trafic pe căutări pe care site-ul nu le acoperea și susține restul paginilor.',
	'seo-15': 'Numărul de rapoarte din Google Analytics și Search Console pe care le configurăm și le urmărim pentru tine: trafic, surse, conversii, pagini de intrare, erori.',
	'seo-16': 'Cod structurat (JSON-LD) adăugat în pagini, prin care Google înțelege exact ce oferi și poate afișa rezultate îmbogățite: stele, prețuri, program, întrebări frecvente.',
	'seo-17': 'Numărul de linkuri toxice pe care le identificăm și le respingem (disavow) lunar. Linkurile din site-uri dubioase pot afecta încrederea Google în domeniul tău.',
	'seo-18': 'Urmărim cei trei indicatori de viteză și stabilitate măsurați de Google (Core Web Vitals) și intervenim în cod când paginile devin lente sau se mișcă la încărcare.',
	'seo-19': 'Optimizăm codul, imaginile și cache-ul pentru un scor Google PageSpeed de cel puțin 80. Paginile rapide rețin vizitatorii, iar viteza contează în clasament.',
	'seo-20': 'Publicăm articole pe site-uri de presă și de nișă, cu link către site-ul tău. Obții mențiuni pe surse cunoscute, autoritate în ochii Google și vizitatori din acele articole.',
	'seo-21': 'Adăugăm semnalele de competență și încredere cerute de Google: autori reali cu biografie, surse citate, date de contact, politici. Contează mai ales în domenii sensibile.',
	'seo-23': 'Pagini locale și fișe Google Business separate pentru fiecare oraș în care activezi, ca să fii găsit în căutările locale din fiecare zonă, pe lângă cea a sediului.',
	'seo-24': 'Ore de lucru tehnic pe site incluse lunar: actualizări, mici modificări, remedieri. Recomandările SEO se pot implementa direct, fără să cauți alt furnizor.',
	'aeo-1': 'Verificăm la început cât de des și în ce context apare brandul tău în răspunsurile AI. Este punctul de referință față de care măsurăm progresul ulterior.',
	'aeo-2': 'Motoarele AI în care urmărim dacă și cum este menționat brandul tău. Fiecare platformă are surse și comportament propriu, deci numărul lor contează.',
	'aeo-3': 'Numărul de întrebări tip client (ex. „ce firmă de X recomanzi în Y”) pe care le testăm lunar în motoarele AI, ca să vedem dacă ești menționat și în ce fel.',
	'aeo-4': 'Adaptăm conținutul ca să poată fi preluat în rezumatele AI afișate de Google deasupra rezultatelor clasice, acolo unde ajung tot mai multe căutări.',
	'aeo-5': 'Structurăm răspunsuri scurte și clare la întrebările frecvente, ca paginile tale să apară în caseta evidențiată din Google și în secțiunea „Oamenii întreabă și”.',
	'aeo-6': 'Descriem în cod structurat cine este firma, cine sunt oamenii și ce produse oferi, ca motoarele AI să le recunoască drept entități clare, cu nume și relații între ele.',
	'aeo-7': 'Publicăm un fișier llms.txt care rezumă site-ul pentru modelele AI și ne asigurăm că boții ChatGPT, Claude și Perplexity pot accesa și citi conținutul.',
	'aeo-8': 'Numărul de pagini existente pe care le rescriem lunar în format ușor de citat de AI: răspuns direct la început, subtitluri clare, liste și definiții scurte.',
	'aeo-9': 'Articole noi, scrise de la zero ca răspuns la întrebările pe care clienții le pun motoarelor AI, pe subiecte unde brandul tău nu este încă menționat.',
	'aeo-10': 'Construim pagini cu întrebări și răspunsuri și le marcăm cu FAQPage schema, un format pe care Google și motoarele AI îl preiau cu ușurință în răspunsuri.',
	'aeo-11': 'Creăm studii, cifre și statistici originale din datele afacerii tale. Datele proprii sunt genul de sursă pe care articolele și modelele AI ajung să o citeze.',
	'aeo-12': 'Pagini de autor cu biografie, credențiale și surse citate în articole. Motoarele AI dau mai multă greutate conținutului atribuit unor experți identificabili.',
	'aeo-13': 'Înregistrăm și consolidăm brandul ca entitate în Wikidata și în Knowledge Graph-ul Google, bazele de date pe care AI-urile le folosesc ca să verifice cine ești.',
	'aeo-14': 'Construim prezență în discuțiile de pe Reddit, Quora și forumuri de nișă, surse pe care modelele AI le citesc frecvent când formulează recomandări.',
	'aeo-15': 'Lucrăm să fii inclus în topuri și articole comparative („cele mai bune X din Y”), pe care AI-urile le folosesc adesea ca sursă pentru recomandări.',
	'aeo-16': 'Măsurăm cât de des ești menționat în răspunsurile AI față de concurenți, la aceleași întrebări. Arată cine domină conversația în nișa ta și unde poți recupera.',
	'aeo-17': 'Primești lunar în CRM lista răspunsurilor AI în care apare brandul, cu platforma, întrebarea și contextul, plus evoluția față de luna anterioară.',
	'aeo-18': 'Datele de vizibilitate AI se actualizează săptămânal în CRM, ca să observi schimbările la câteva zile după ce apar, nu după o lună.',
	'aeo-19': 'Primești o notificare când brandul dispare dintr-un răspuns AI în care era menționat, ca să putem reacționa înainte ca pierderea să se extindă.',
	'aeo-20': 'Optimizăm fișele de produs (date, prețuri, stoc, recenzii) pentru ca produsele tale să apară în recomandările de cumpărături generate de motoarele AI.',
	'aeo-21': 'Canalul prin care ne poți contacta pentru întrebări despre serviciu. Telefonul înseamnă răspuns mai rapid pentru situațiile urgente.',
	'aeo-22': 'Un specialist îți explică ce se schimbă în căutarea AI și ce înseamnă pentru afacerea ta, cu recomandări concrete de conținut și poziționare.',
	'aeo-23': 'Întâlnire lunară online în care trecem prin rezultate, stabilim prioritățile pentru luna următoare și răspundem la întrebările echipei tale.',
	'wp-1': 'Verificăm automat, permanent, dacă site-ul este accesibil și cât de repede răspunde. Aflăm de o cădere înainte să o observe clienții tăi.',
	'wp-2': 'Frecvența cu care instalăm versiunile noi ale temelor și pluginurilor gratuite. Actualizările închid breșe de securitate și previn erorile de compatibilitate.',
	'wp-3': 'Frecvența cu care salvăm automat o copie completă a site-ului (fișiere și bază de date). Cu cât este mai des, cu atât pierzi mai puțin dacă ceva se strică.',
	'wp-4': 'Scanăm periodic fișierele site-ului după cod malițios și îl eliminăm când apare. Un site infectat poate fi blocat de Google și marcat ca periculos în browsere.',
	'wp-5': 'Curățăm baza de date de revizii vechi, comentarii spam și date temporare. O bază de date mai mică înseamnă pagini care se încarcă mai repede.',
	'wp-6': 'Canalul prin care ne semnalezi probleme și primești ajutor. Telefonul este util pentru situațiile care nu pot aștepta un răspuns scris.',
	'wp-7': 'Setăm reguli de protecție: autentificare în doi pași, limitarea încercărilor de login, blocarea accesului la fișiere sensibile, permisiuni corecte.',
	'wp-8': 'Solicitările tale intră înaintea celorlalte în coada de lucru și sunt preluate cu un timp de răspuns mai scurt.',
	'wp-9': 'Dezvoltăm funcții noi adaptate afacerii tale (formulare speciale, calculatoare de preț, integrări), dincolo de ce oferă pluginurile standard.',
	'wp-10': 'Poți cere oricând o copie completă a site-ului, de exemplu înainte de o modificare importantă, ca să o poți restaura dacă ceva nu merge cum trebuie.',
	'wp-11': 'Verificăm la intervale regulate utilizatorii, permisiunile, pluginurile abandonate și setările, ca să găsim punctele slabe înainte să le găsească altcineva.',
	'wp-12': 'Instalăm și configurăm pluginurile noi de care ai nevoie (formulare, rezervări, magazin), verificând că nu intră în conflict cu cele existente.',
	'wp-13': 'Când site-ul cade sau afișează erori care blochează vânzările, intervenim ca să-l readucem online și căutăm cauza, ca problema să nu revină.',
	'wp-14': 'Punem site-ul în spatele rețelei Cloudflare: conținutul se livrează din servere apropiate de vizitator, iar traficul suspect este filtrat înainte să ajungă la tine.',
	'wp-15': 'Primești săptămânal în contul CRM un sumar cu actualizările făcute, backup-urile realizate, timpul de funcționare și incidentele apărute.',
	'wp-16': 'Raport lunar în CRM cu evoluția performanței, a securității și a lucrărilor efectuate, ca să vezi starea generală a site-ului dintr-o privire.',
	'wp-17': 'Ore de dezvoltare incluse lunar pentru modificări care nu țin de mentenanță: secțiuni noi, ajustări de design, schimbări de funcționalitate.',
	'wp-18': 'Gestionăm noi reînnoirea anuală a domeniului, ca site-ul și adresele de e-mail să nu se oprească din cauza unei plăți uitate sau a unui termen ratat.',
	'wp-19': 'Actualizăm și pluginurile și temele cu licență plătită (Elementor Pro, WPML etc.), care cer licență activă și verificare manuală la fiecare versiune nouă.',
	'wp-20': 'Te anunțăm din timp când domeniul se apropie de expirare, ca să ai timp să îl prelungești și să nu riști să îl pierzi sau să rămâi cu site-ul oprit.',
	'wp-21': 'Instalăm certificatul SSL (lacătul din browser, https), îl reînnoim la timp și verificăm că nu expiră. Fără el, browserele marchează site-ul ca nesigur.',
	'wp-22': 'Verificăm că site-ul respectă regulile GDPR (politici, formulare, cookie-uri) și instalăm bannerul de consimțământ cerut de lege, configurat corect.',
	'wp-23': 'Firewall pentru aplicații web (WAF) care filtrează atacurile (injecții, forță brută, boți) înainte să ajungă la WordPress, nu după ce au produs daune.',
	'wp-24': 'O copie de test a site-ului, invizibilă publicului, unde verificăm actualizările și modificările mari înainte să le aplicăm pe site-ul real.',
	'wp-25': 'Ținem codul personalizat al site-ului într-un sistem de versionare (Git): orice modificare este înregistrată și poate fi anulată dacă apare o problemă.',
	'cro-1': 'În prima lună analizăm cum parcurg vizitatorii site-ul, unde se blochează și ce îi oprește să cumpere sau să te contacteze. Este baza planului de optimizare.',
	'cro-2': 'Instalăm instrumente care arată unde dau clic și cât derulează vizitatorii (heatmap) și înregistrează sesiuni anonime, ca să vedem exact unde se pierd.',
	'cro-3': 'Numărul de experimente pe care le rulăm în paralel. Un test A/B arată două variante ale unei pagini unor vizitatori diferiți și măsoară care convertește mai bine.',
	'cro-4': 'Urmărim fiecare pas de la prima vizită până la comandă sau cerere de ofertă și identificăm etapa în care pierzi cei mai mulți clienți potențiali.',
	'cro-5': 'În fiecare lună primești un document cu observații concrete și propuneri de îmbunătățire, prioritizate după impactul estimat și efortul necesar.',
	'cro-6': 'Instalăm și configurăm platforma cu care rulăm testele A/B, integrată cu analytics, ca rezultatele să fie măsurate corect de la primul experiment.',
	'cro-7': 'Numărul de machete de design (butoane, secțiuni, pagini) pe care le pregătim lunar pentru testele A/B. Fără variante noi, testele nu pot continua.',
	'cro-8': 'Vezi în contul CRM rezultatele testelor: variantele comparate, ratele de conversie, semnificația statistică și decizia luată pe baza lor.',
	'cro-9': 'Pagini de destinație noi, concepute, scrise și publicate de noi pentru campanii sau oferte specifice, cu un singur obiectiv clar de conversie.',
	'cro-10': 'Refacem paginile existente care nu convertesc (structură, design, mesaje), pe baza datelor din analize și teste, nu după preferințe estetice.',
	'cro-11': 'Ajustăm textele mici, dar decisive: etichete de butoane, mesaje de eroare, explicații din formulare. Adesea fac diferența între abandon și finalizare.',
	'cro-12': 'Reducem câmpurile inutile, clarificăm erorile și ordinea pașilor din formulare, locul în care se pierd mulți clienți deja aproape convinși.',
	'cro-13': 'Analize și teste separate pentru vizitatorii de pe telefon, care au alt comportament și alte obstacole decât cei de pe desktop.',
	'cro-14': 'Afișăm conținut diferit în funcție de vizitator: sursa din care vine, orașul, dacă a mai fost pe site. Un mesaj potrivit convinge mai ușor decât unul generic.',
	'cro-15': 'Sincronizăm lansarea paginilor și a testelor cu campaniile tale de Ads, ca traficul plătit să ajungă pe pagini pregătite special pentru el.',
	'cro-16': 'Folosim modele statistice pe datele istorice ca să estimăm ce segmente de vizitatori au șanse mari să convertească și unde merită să intervenim mai întâi.',
	'cro-17': 'Discuție săptămânală cu specialistul CRO: rezultate, ipoteze noi, decizii rapide. Ritmul săptămânal ține testele în mișcare și scurtează drumul până la rezultate.',
	'em-1': 'Configurăm contul și înregistrările DNS care autentifică domeniul tău (SPF, DKIM, DMARC). Fără ele, emailurile riscă să ajungă în spam sau să fie respinse.',
	'em-2': 'Șabloane de email în culorile brandului, care se afișează corect pe telefon și pe desktop. Numărul indică câte machete distincte primești.',
	'em-3': 'Numărul de campanii pe care le pregătim și le trimitem noi în fiecare lună, de la conținut la programare. Tu aprobi, noi ne ocupăm de restul.',
	'em-4': 'Împărțim abonații în grupuri după interese, comportament sau istoric, ca fiecare să primească mesaje relevante. Mai multe segmente înseamnă mesaje mai bine țintite.',
	'em-5': 'Testăm două variante de subiect sau de conținut pe o parte din listă, iar restul primește varianta câștigătoare. Decizii pe date, nu pe presupuneri.',
	'em-6': 'Serie de emailuri trimise automat după abonare: cine ești, ce oferi, care e primul pas. Valorifică momentul în care interesul abonatului este cel mai ridicat.',
	'em-7': 'Email automat către clienții care au pus produse în coș și nu au finalizat comanda. Îți dă șansa să recuperezi comenzi care altfel s-ar pierde.',
	'em-8': 'Secvență automată după comandă: confirmare, sfaturi de utilizare, cerere de recenzie, produse complementare. Pregătește terenul pentru a doua achiziție.',
	'em-9': 'Secvență automată pentru abonații care nu au mai deschis emailuri de mult timp. Îi readuce pe cei încă interesați și curăță lista de adresele inactive.',
	'em-10': 'Mesaj automat de ziua abonatului sau la aniversarea primei comenzi, de obicei însoțit de o ofertă. Un gest personal care întreține relația cu clientul.',
	'em-11': 'Blocuri de conținut care se schimbă în funcție de destinatar: produse văzute, oraș, istoric de cumpărare. Același email, relevant pentru fiecare abonat.',
	'em-12': 'Textele campaniilor sunt scrise de un copywriter, adaptate tonului brandului și obiectivului fiecărui email. Tu nu mai pierzi timp cu redactarea.',
	'em-13': 'Creăm materiale gratuite (ghid, checklist, reducere) și formulare de abonare care aduc constant adrese noi. Lista crește cu oameni cu adevărat interesați.',
	'em-14': 'Urmărim reputația domeniului, rata de respingere și plasarea în inbox, apoi intervenim la primele semne de problemă. Un email care nu ajunge nu vinde.',
	'em-15': 'Vezi în portalul tău de client rezultatele fiecărei campanii: câți au deschis, câți au dat clic, câți au cumpărat. Fără fișiere Excel trimise manual.',
	'em-16': 'Conectăm platforma de email cu site-ul și CRM-ul tău, astfel încât abonații noi, comenzile și datele de contact se sincronizează automat, fără export manual.',
	'em-17': 'Lista de abonați se sincronizează cu Facebook și Instagram Ads, ca să le arăți reclame abonaților existenți sau să găsești persoane asemănătoare lor.',
	'em-18': 'Adăugăm SMS-ul ca al doilea canal, din aceeași platformă: confirmări, oferte cu termen limită, remindere. Potrivit pentru mesajele care trebuie văzute rapid.',
	'em-19': 'Notificări scurte trimise în browser sau pe telefon celor care și-au dat acordul, fără să ai nevoie de adresa lor de email. Un canal în plus pentru oferte și noutăți.',
	'ma-1': 'Analizăm cum ajunge un lead de la primul contact la vânzare: surse, pași, timpi de răspuns, unde se pierd oportunități. Pe această bază construim automatizările.',
	'ma-2': 'Conectăm platforma de automatizare cu CRM-ul tău actual, ca leadurile, etapele și activitățile să circule automat între sisteme. Fără introducere dublă de date.',
	'ma-3': 'Fiecare lead primește automat un punctaj după profil și comportament (pagini vizitate, emailuri deschise). Echipa de vânzări știe pe cine să sune mai întâi.',
	'ma-4': 'Secvențe automate care țin legătura cu leadurile încă nepregătite să cumpere. Fiecare flow acoperă un scenariu: ofertă cerută, demo făcut, client inactiv.',
	'ma-5': 'Configurăm contul oficial WhatsApp Business și îl legăm la automatizări: confirmări, remindere, răspunsuri la întrebări frecvente, pe canalul folosit zilnic de clienți.',
	'ma-6': 'Asistent automat pe site care răspunde la întrebări frecvente, califică vizitatorii și preia date de contact, oricând. Îl instruim pe informațiile afacerii tale.',
	'ma-7': 'Același asistent automat, extins pe Messenger și Instagram Direct: răspunde la mesaje și comentarii, preia comenzi sau programări și trimite leadurile în CRM.',
	'ma-8': 'Adăugăm SMS-ul în automatizări: remindere de programare, confirmări, oferte cu termen limită. Potrivit pentru mesajele care trebuie văzute rapid.',
	'ma-9': 'Scenarii care leagă mai multe canale: un lead din reclamă primește email, apoi SMS dacă nu răspunde, apoi ajunge ca task la vânzări. Totul rulează automat.',
	'ma-10': 'Automatizăm pașii repetitivi dintre primul contact și contract: alocarea leadului, follow-up programat, reminder la oferte fără răspuns. Vânzările rămân cu discuțiile.',
	'ma-11': 'Raport care arată toate punctele de contact dinaintea unei vânzări (reclamă, email, organic), în loc să atribuie totul ultimului clic. Vezi ce canale merită bugetul.',
	'ma-12': 'Testăm variante ale automatizărilor (mesaj, moment de trimitere, ordinea pașilor) pe segmente paralele și păstrăm varianta cu rezultate mai bune.',
	'ma-13': 'Trimitem conversiile direct din CRM către Google și Meta, de pe server, nu din browser. Platformele optimizează pe vânzări reale, chiar și cu cookie-uri blocate.',
	'ma-14': 'Un model de învățare automată învață din istoricul tău de vânzări și estimează probabilitatea de conversie a fiecărui lead nou, fără reguli setate manual.',
	'ma-15': 'Conectăm instrumente care nu comunică nativ între ele (formulare, facturare, calendar, ERP) prin API sau Zapier. Numărul indică câte astfel de conexiuni sunt incluse.',
	'ma-16': 'Rezultatele automatizărilor (leaduri, rate de răspuns, conversii) apar în portalul tău de client, actualizate în timp real, fără să ceri rapoarte.',
	'ma-17': 'Întâlnire lunară în care trecem prin rezultate, ajustăm prioritățile și planificăm următoarele automatizări. Strategia se adaptează la ce se întâmplă în afacerea ta.',
	'ma-18': 'Ore lunare cu un specialist pentru întrebări, optimizări sau cerințe noi, în afara întâlnirii strategice. Le folosești cum ai nevoie, pe parcursul lunii.',
	'gs-1': 'Instalăm Google Tag Manager (GTM), containerul din care se gestionează toate codurile de măsurare, și configurăm evenimentele: apel, formular, WhatsApp, Messenger.',
	'gs-2': 'Configurăm Google Analytics 4 conectat la GTM, cu măsurare avansată activată, și importăm conversiile în Google Ads, ca datele să fie consecvente între platforme.',
	'gs-3': 'Activăm Enhanced Conversions (date de conversie mai complete, trimise securizat) și conectăm Search Console, ca să vezi și ce caută oamenii organic.',
	'gs-4': 'Setăm strategiile de licitare potrivite obiectivului, excluderile de locații, termeni și plasamente, plus programul orar de afișare, ca bugetul să nu se irosească.',
	'gs-5': 'Organizăm contul pe campanii cu roluri clare: Brand (cei care te caută deja), Search (cereri de produs) și Performance Max (toate canalele Google).',
	'gs-6': 'Construim grupurile de anunțuri, scriem headline-uri în variante pentru testare A/B, adăugăm liste de cuvinte negative și listele de remarketing.',
	'gs-7': 'Implementăm Consent Mode v2 prin GTM: măsurarea respectă alegerea vizitatorilor la bannerul de cookie-uri, conform GDPR, fără să pierzi complet datele.',
	'gs-8': 'Timpul estimat de la primirea acceselor până la finalizarea implementării GTM și GA4, inclusiv testarea evenimentelor. Depinde și de accesul la site.',
	'gs-9': 'Timpul estimat pentru construirea campaniilor după ce măsurarea funcționează: structură, cuvinte-cheie, anunțuri, extensii, setări și verificare înainte de lansare.',
	'gs-10': 'Perioada în care urmărim zilnic campaniile după lansare, corectăm erorile de măsurare și facem primele optimizări, până când conturile se stabilizează.',
	'web-1': 'Numărul maxim de pagini distincte pe care le construim și le populăm cu conținut: acasă, despre noi, servicii, contact, blog. Gândește-te la structura de care ai nevoie.',
	'web-2': 'Pornim de la o temă WordPress premium, licențiată și actualizată, adaptată la culorile, fonturile și structura brandului tău. Mai rapid decât un design de la zero.',
	'web-2b': 'Designul este creat de la zero în Figma, pe nevoile tale, și abia apoi implementat în WordPress. Nu pornim de la un șablon, deci site-ul nu seamănă cu altele.',
	'web-3': 'Site-ul este gândit întâi pentru telefon, apoi adaptat la tabletă și desktop. Majoritatea vizitatorilor vin de pe mobil, iar Google indexează versiunea mobilă.',
	'web-4': 'Configurăm elementele tehnice de care Google are nevoie: titluri și descrieri, date structurate (schema), sitemap, plugin Yoast. Baza pentru a fi găsit în căutări.',
	'web-5': 'Instalăm Google Analytics 4 prin Google Tag Manager, ca să vezi de unde vin vizitatorii și ce fac pe site. Tag Manager permite adăugarea altor scripturi fără cod.',
	'web-6': 'Conectăm site-ul la Search Console, instrumentul gratuit Google care arată pe ce căutări apari, erorile de indexare și problemele de pe mobil.',
	'web-7': 'Formulare cu logică condiționată, câmpuri multiple, încărcare de fișiere și notificări pe email. Cererile ajung la tine structurat, nu într-un mesaj fără detalii.',
	'web-8': 'Sesiuni în care te învățăm să modifici texte, imagini și pagini singur, fără să depinzi de noi. Numărul de ore indică durata totală a instruirii.',
	'web-9': 'După lansare ne ocupăm de actualizări WordPress și pluginuri, copii de siguranță și mici corecții, pe perioada indicată în luni. Site-ul rămâne sigur și funcțional.',
	'web-10': 'Includem un modul complex la alegere: programări online, zonă cu acces pe bază de cont sau conectare la un sistem extern prin API. Site-ul devine un instrument de lucru.',
	'web-11': 'Site-ul poate fi afișat în mai multe limbi, cu URL-uri separate pentru fiecare și interfața tradusă. Necesar dacă ai clienți din afara României.',
	'web-12': 'Formularele de pe site trimit datele automat în CRM-ul și platforma ta de email (HubSpot, Mailchimp etc.). Niciun lead nu rămâne uitat într-un inbox.',
	'web-13': 'Certificat SSL (conexiune criptată, lacătul din browser) și banner de consimțământ pentru cookie-uri conform GDPR. Cerute de legislație, de Google și de vizitatori.',
	'web-14': 'Optimizăm viteza de încărcare (imagini, cache, scripturi) până la un scor Google PageSpeed de cel puțin 80. Un site lent pierde vizitatori și poziții în căutări.',
	'web-15': 'O rundă de revizii înseamnă un set de modificări cerute de tine după o prezentare intermediară. Numărul arată de câte ori putem ajusta designul până la varianta finală.',
	'web-16': 'Estimarea de timp de la primirea conținutului și a materialelor de brand până la lansare. Depinde și de cât de repede primim feedback și aprobări de la tine.',
	'wc-1': 'Tehnologia de bază, aleasă după complexitate: Astro pentru site-uri de conținut, Next.js când ai nevoie de logică proprie și API. Cod scris de noi, nu șablon.',
	'wc-2': 'Numărul maxim de pagini distincte proiectate și implementate. Paginile generate automat dintr-un șablon (de exemplu articolele de blog) se numără o singură dată.',
	'wc-3': 'Fiecare ecran este desenat în Figma pe brandul tău, apoi scris în cod, fără teme sau șabloane de la terți. Rezultatul este unic și nu cară funcții de care nu ai nevoie.',
	'wc-4': 'Lighthouse este instrumentul Google care notează viteza, accesibilitatea și SEO-ul unei pagini de la 0 la 100. Scorul țintă este pragul urmărit la lansare.',
	'wc-5': 'Cum îți modifici conținutul după lansare: de la fișiere simple editate de noi, la un panou de administrare în care schimbi texte și imagini singur, fără programator.',
	'wc-6': 'Cum sunt generate paginile: SSG le construiește dinainte (foarte rapide), ISR le actualizează periodic, SSR le generează la fiecare cerere, cu conținut mereu la zi.',
	'wc-7': 'Tranziții și animații fluide la derulare, la hover sau între pagini, implementate cu biblioteci specializate. Site-ul capătă dinamism fără să piardă din viteză.',
	'wc-8': 'Pregătim tot ce citesc motoarele de căutare: titluri și descrieri, date structurate (schema), sitemap și robots.txt. Fundația pentru ca paginile să fie indexate corect.',
	'wc-9': 'Instalăm Google Analytics 4, Google Tag Manager și pixelul Meta. Măsori traficul și conversiile și poți rula campanii de remarketing din prima zi.',
	'wc-10': 'Conectăm site-ul la sisteme externe: CRM pentru leaduri, Stripe pentru plăți, webhook-uri pentru notificări automate. Numărul indică câte conexiuni sunt incluse.',
	'wc-11': 'Site-ul este construit să funcționeze în mai multe limbi, cu URL-uri și metadate separate pentru fiecare. Extinderea pe o piață nouă nu mai cere refacerea site-ului.',
	'wc-12': 'Secțiune de articole cu pagini generate automat, categorii, etichete și flux RSS. Publici conținut nou regulat, un factor important pentru vizibilitatea în căutări.',
	'wc-13': 'Formulare cu pași multipli, validare în timp real și protecție anti-spam, scrise de noi după nevoile tale. Datele ajung curate și complete în sistemul ales.',
	'wc-14': 'Conturi de utilizator cu înregistrare, autentificare și resetare de parolă, inclusiv prin Google sau conturi sociale. Necesar pentru zone private sau portaluri.',
	'wc-15': 'Bază de date proprie, proiectată pentru datele afacerii tale: comenzi, utilizatori, rezervări. Site-ul poate funcționa ca o aplicație completă, cu conturi și istoric.',
	'wc-16': 'Fiecare modificare de cod este testată și publicată automat, fără pași manuali. Actualizările ajung live rapid, iar o eroare poate fi anulată în câteva minute.',
	'wc-17': 'După lansare corectăm erorile apărute, actualizăm dependențele și răspundem la întrebări tehnice, pe perioada indicată în luni.',
	'wc-18': 'Estimarea de la aprobarea designului până la lansare. Site-urile custom durează mai mult decât cele pe șablon, pentru că fiecare componentă este scrisă de la zero.',
	'woo-1': 'Numărul maxim de produse pe care le introducem și le configurăm noi (descrieri, imagini, prețuri, categorii). Ulterior poți adăuga singur altele.',
	'woo-2': 'Un produs poate avea mai multe variante cu stoc și preț propriu (mărime, culoare, material). Clientul alege varianta din aceeași pagină, fără produse duplicate.',
	'woo-3': 'Filtrare după preț, atribute și categorii, plus recenzii cu stele lăsate de cumpărători. Clienții găsesc repede ce caută și au încredere în ce văd.',
	'woo-4': 'Metodele de plată la finalizarea comenzii: de la ramburs la card, Apple/Google Pay sau rate. Mai multe opțiuni de plată, mai puține comenzi abandonate.',
	'woo-5': 'Comanda generează automat AWB-ul (eticheta de transport) și îl trimite curierului, iar clientul primește codul de urmărire. Fără completat manual în platforma curierului.',
	'woo-6': 'Factura se emite automat la fiecare comandă și se transmite în SPV (sistemul ANAF pentru e-Factura), conform legislației. Contabilitatea primește totul fără intervenție.',
	'woo-7': 'Optimizăm paginile de produs și de categorie pentru căutări și configurăm urmărirea e-commerce în GA4: vezi ce produse se văd, se adaugă în coș și se cumpără.',
	'woo-8': 'Hărți de căldură și înregistrări anonime ale sesiunilor arată unde dau clic vizitatorii și unde se blochează, ca să înțelegi de ce nu ajung să cumpere.',
	'woo-9': 'Recomandări automate de produse complementare sau superioare, în pagina de produs, în coș și pe email după comandă. Scopul este o valoare mai mare pe fiecare comandă.',
	'woo-10': 'Sincronizăm magazinul cu programul tău de gestiune sau contabilitate: stocuri, comenzi, clienți și facturi circulă automat între sisteme. Fără introduceri duble.',
	'woo-11': 'Stocul se actualizează instant la fiecare comandă, retur sau recepție, cu alerte la prag minim. Nu vinzi produse pe care nu le mai ai în depozit.',
	'woo-12': 'Cotele de TVA se aplică automat per produs și după țara cumpărătorului (inclusiv livrări în UE), iar prețurile se afișează corect cu TVA inclus.',
	'woo-13': 'Clientul primește automat confirmarea comenzii, anunțul de expediere și codul de urmărire. Varianta cu SMS adaugă mesaje text pentru momentele importante.',
	'woo-14': 'Catalogul se sincronizează cu Facebook și Instagram, ca reclamele să arate automat produsele văzute de fiecare vizitator. Baza pentru remarketing dinamic.',
	'woo-15': 'Generăm și actualizăm automat fluxul de produse pentru Google Merchant Center. Produsele tale pot apărea în rezultatele Google Shopping, cu poză și preț.',
	'woo-16': 'Magazinul poate fi afișat în mai multe limbi, cu produse, categorii și pagini de finalizare a comenzii traduse. Necesar dacă vinzi și în afara României.',
	'woo-17': 'Machetele magazinului sunt desenate de la zero pentru brandul tău, nu adaptate dintr-o temă. Pagina de produs, coșul și finalizarea comenzii arată exact cum vrei.',
	'woo-18': 'Te învățăm să administrezi magazinul: adăugare produse, procesare comenzi, retururi, cupoane, rapoarte. Numărul de ore indică durata totală a instruirii.',
	'woo-19': 'Mutăm produsele, clienții, comenzile și recenziile din magazinul actual, cu redirecționări de la vechile URL-uri. Păstrezi istoricul și protejezi pozițiile în căutări.',
	'woo-20': 'După lansare rezolvăm erorile apărute, actualizăm WooCommerce și pluginurile și răspundem la întrebări, pe perioada indicată în luni.',
	'app-1': 'Hibrid și Flutter/React Native folosesc un singur cod pentru iOS și Android; nativ înseamnă cod separat per platformă, cu acces complet la funcțiile telefonului.',
	'app-2': 'Numărul de ecrane distincte proiectate și implementate (login, listă, detaliu, profil, setări). Fiecare ecran înseamnă design, dezvoltare și testare separată.',
	'app-3': 'Cum se conectează utilizatorii: email și parolă, conturi sociale (Facebook, Apple, Google), amprentă sau Face ID, până la SSO pentru aplicații de companie.',
	'app-4': 'Notificări trimise pe telefonul utilizatorilor chiar și când aplicația este închisă: oferte, statusuri de comandă, remindere. Canal direct, gestionat din Firebase.',
	'app-5': 'Listă de produse sau servicii cu căutare, filtre și pagini de detaliu, plus posibilitatea de a salva favorite. Utilizatorii revin la ce i-a interesat.',
	'app-6': 'Cumpărare completă din aplicație: coș, adresă, plată cu cardul prin procesatori acreditați. Plata se face în câteva atingeri, fără redirecționare către site.',
	'app-7': 'Utilizatorul își vede comenzile anterioare și statusul lor și își administrează datele de profil și adresele. Mai puține întrebări la suport, recomenzi mai ușoare.',
	'app-8': 'Utilizatorii pot nota și comenta produsele sau serviciile direct din aplicație. Feedbackul public ajută alți clienți să decidă și îți arată ce este de îmbunătățit.',
	'app-9': 'Partea de server care ține datele și logica: de la conținut fix în aplicație, la Firebase (rapid de pus în funcțiune), până la server propriu pe AWS/GCP, scalabil.',
	'app-10': 'Interfață documentată prin care aplicația comunică cu serverul și prin care alte sisteme (site, ERP, parteneri) pot folosi aceleași date.',
	'app-11': 'Mesagerie instantanee în aplicație, între utilizatori sau între client și echipa ta, cu notificări și istoric. Pentru suport, comunități sau platforme de tip marketplace.',
	'app-12': 'Hărți integrate, localizarea utilizatorului, calcul de distanțe și trasee. Necesar pentru livrări, rezervări la locații fizice sau servicii din apropiere.',
	'app-13': 'Funcții bazate pe inteligență artificială: recomandări personalizate, căutare vizuală, asistent conversațional sau recunoaștere de imagini, alese după nevoile tale.',
	'app-14': 'Aplicația schimbă date automat cu sistemele tale interne: stocuri, prețuri, comenzi, clienți. Informația este aceeași în aplicație, în magazin și în contabilitate.',
	'app-15': 'Testăm aplicația pe mai multe modele de telefon și versiuni de sistem, manual și automat, înainte de publicare. Mai puține erori ajung la utilizatori.',
	'app-16': 'Ne ocupăm de conturile de dezvoltator, materialele cerute, trimiterea spre aprobare și corecțiile cerute de Apple și Google. Nu treci singur prin procesul de aprobare.',
	'app-17': 'După lansare corectăm erorile raportate, actualizăm aplicația la noile versiuni iOS și Android și monitorizăm stabilitatea, pe perioada indicată în luni.',
	'app-18': 'Estimarea de la aprobarea designului până la publicarea în magazine, inclusiv testarea și aprobarea Apple/Google. Depinde de viteza feedbackului tău la fiecare etapă.',
	'lp-1': 'Numărul de landing page-uri distincte, fiecare cu un singur obiectiv și un singur public (de exemplu, o pagină per campanie sau per serviciu).',
	'lp-2': 'Pagina este proiectată și scrisă în cod pentru brandul tău, nu asamblată într-un editor drag-and-drop. Se încarcă mai repede și arată exact cum vrei.',
	'lp-3': 'Textele paginii sunt scrise de un copywriter, iar titlul principal este testat în mai multe variante. Mesajul decide dacă vizitatorul rămâne sau pleacă.',
	'lp-4': 'Formular scurt, cu câmpurile strict necesare, validare clară și protecție anti-spam. Fiecare câmp în plus scade numărul celor care îl completează.',
	'lp-5': 'Instalăm Google Analytics 4 prin Tag Manager și definim evenimentele importante (trimitere formular, clic pe telefon). Știi exact de unde vin conversiile.',
	'lp-6': 'Instalăm pixelul Meta și configurăm evenimentul de conversie (lead, achiziție). Facebook și Instagram Ads pot optimiza livrarea reclamelor pe rezultate reale.',
	'lp-7': 'Hărți de căldură și înregistrări anonime ale vizitelor arată până unde derulează oamenii și unde ezită. Afli ce îi oprește să completeze formularul.',
	'lp-8': 'Configurăm un instrument care împarte traficul între două variante ale paginii și măsoară care convertește mai bine. Decizii pe date, nu pe gust.',
	'lp-9': 'Numărul de machete alternative ale paginii (alt titlu, altă imagine, altă așezare) pregătite pentru testare. Fiecare variantă este o ipoteză de verificat.',
	'lp-10': 'Integrăm video de prezentare, animații sau galerii interactive, optimizate să nu încetinească pagina. Util când produsul se explică mai bine vizual.',
	'lp-11': 'Versiunea de mobil nu este doar o comprimare a celei de desktop: butoanele, formularul și ordinea secțiunilor sunt gândite separat pentru telefon.',
	'lp-12': 'Optimizăm imaginile, scripturile și încărcarea până la un scor Google PageSpeed de cel puțin 90. Fiecare secundă în plus pierde vizitatori veniți din reclame.',
	'lp-13': 'După lansare rulăm teste A/B pe traficul real și ajustăm pagina după rezultate, pe numărul de zile indicat. Optimizarea adevărată începe după ce pagina este live.',
	'lp-14': 'La final primești un raport cu rata de conversie, sursele de trafic care au funcționat și recomandări concrete pentru creșterea bugetului sau extinderea campaniei.',
	'lp-15': 'O rundă de revizii înseamnă un set de modificări cerute de tine după o prezentare intermediară. Numărul arată de câte ori putem ajusta pagina până la varianta finală.',
};
