// This file is auto-generated by scripts/generate-sitemap.ts
// Do not edit manually. Run `pnpm generate:sitemap` to regenerate.

import { db } from '$lib/server/db';
import * as table from '$lib/server/db/schema';
import { eq } from 'drizzle-orm';
import { getBlogPosts } from '$lib/remotes/blog.remote';
import { getProjects } from '$lib/remotes/project.remote';
import type { RequestHandler } from './$types';

const LANGUAGES = ['ro', 'en'] as const;

// Static routes scanned at generation time
const STATIC_ROUTES = [
	'/contact',
	'/privacy',
	'/',
	'/terms',
	'/blog',
	'/work',
	'/cookies'
] as const;

/**
 * Get lastmod date for a route path from PageSEO settings
 * Returns the latest updatedAt from pageSeo or any of its translations
 */
async function getRouteLastmod(path: string): Promise<Date | null> {
	try {
		const [pageSeo] = await db
			.select({
				id: table.pageSeo.id,
				updatedAt: table.pageSeo.updatedAt
			})
			.from(table.pageSeo)
			.where(eq(table.pageSeo.path, path))
			.limit(1);

		if (!pageSeo) return null;

		// Get all translations to find the latest update
		const translations = await db
			.select({ updatedAt: table.pageSeoTranslation.updatedAt })
			.from(table.pageSeoTranslation)
			.where(eq(table.pageSeoTranslation.pageSeoId, pageSeo.id));

		// Find the latest date from pageSeo or any translation
		const dates = [pageSeo.updatedAt, ...translations.map((t) => t.updatedAt)].filter(
			(d): d is Date => d !== null && d !== undefined
		);

		if (dates.length === 0) return null;

		// Return the most recent date
		const timestamps = dates.map((d) => new Date(d).getTime());
		return new Date(Math.max(...timestamps));
	} catch (error) {
		console.error(`Error fetching lastmod for path ${path}:`, error);
		return null;
	}
}

/**
 * Format date for sitemap (ISO 8601 format)
 */
function formatDate(date: Date | null | undefined): string {
	if (!date) return new Date().toISOString();
	return new Date(date).toISOString();
}

/**
 * Escape XML special characters
 */
function escapeXml(unsafe: string): string {
	return unsafe
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;')
		.replace(/'/g, '&apos;');
}

/**
 * Generate sitemap XML
 */
async function generateSitemapXml(baseUrl: string): Promise<string> {
	const urls: string[] = [];

	// Group URLs by path (without language) to add hreflang
	const urlGroups = new Map<string, Array<{ lang: string; url: string; lastmod?: string }>>();

	// Add static routes for each language
	for (const language of LANGUAGES) {
		for (const route of STATIC_ROUTES) {
			const path = route === '/' ? '' : route;
			const url = `${baseUrl}/${language}${path}`;
			const pathKey = path || '/';

			if (!urlGroups.has(pathKey)) {
				urlGroups.set(pathKey, []);
			}
			urlGroups.get(pathKey)!.push({ lang: language, url });
		}
	}

	// Generate URL entries with hreflang and lastmod from PageSEO
	for (const [pathKey, langUrls] of urlGroups.entries()) {
		// Get lastmod from PageSEO for this route path
		const lastmod = await getRouteLastmod(pathKey);

		for (const { lang, url } of langUrls) {
			const hreflangTags = langUrls
				.map(
					(lu) => `		<xhtml:link rel="alternate" hreflang="${lu.lang}" href="${escapeXml(lu.url)}" />`
				)
				.join('\n');
			const defaultHreflang = `		<xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(langUrls.find((lu) => lu.lang === 'ro')?.url || langUrls[0].url)}" />`;

			urls.push(`
	<url>
		<loc>${escapeXml(url)}</loc>
${hreflangTags}
${defaultHreflang}
		<changefreq>daily</changefreq>
		<priority>0.8</priority>
		<lastmod>${formatDate(lastmod)}</lastmod>
	</url>`);
		}
	}

	// Add getBlogPosts items for /blog route - group by slug for hreflang
	const itemGroups = new Map<
		string,
		Array<{ lang: string; url: string; lastmod?: string; slug: string }>
	>();

	for (const language of LANGUAGES) {
		try {
			const result = await getBlogPosts({
				language: language,
				includeUnpublished: false,
				page: 1,
				pageSize: 1000
			});
			const items = result.posts || result.items || result || [];

			for (const item of items) {
				const slug = item.slug;
				const url = `${baseUrl}/${language}/blog/${escapeXml(slug)}`;
				const lastmod = formatDate(item.updatedAt || item.createdAt);

				if (!itemGroups.has(slug)) {
					itemGroups.set(slug, []);
				}
				itemGroups.get(slug)!.push({ lang: language, url, lastmod, slug });
			}
		} catch (error) {
			console.error(`Error fetching getBlogPosts for ${language}:`, error);
		}
	}

	// Generate URL entries with hreflang
	for (const [slug, langUrls] of itemGroups.entries()) {
		// Try to get lastmod from PageSEO for this route pattern, fallback to entity dates
		const routePattern = `/blog/:slug`;
		let routeLastmod = await getRouteLastmod(routePattern);

		// If no PageSEO entry, use the latest entity date from langUrls
		if (!routeLastmod && langUrls.length > 0) {
			const entityDates = langUrls
				.map((lu) => lu.lastmod)
				.filter((d): d is string => !!d)
				.map((d) => new Date(d).getTime());
			if (entityDates.length > 0) {
				routeLastmod = new Date(Math.max(...entityDates));
			}
		}

		for (const { lang, url, lastmod } of langUrls) {
			// Use PageSEO date if available, otherwise use entity date, otherwise current date
			const finalLastmod = routeLastmod || (lastmod ? new Date(lastmod) : null) || new Date();

			const hreflangTags = langUrls
				.map(
					(lu) => `		<xhtml:link rel="alternate" hreflang="${lu.lang}" href="${escapeXml(lu.url)}" />`
				)
				.join('\n');
			const defaultHreflang = `		<xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(langUrls.find((lu) => lu.lang === 'ro')?.url || langUrls[0].url)}" />`;

			urls.push(`
	<url>
		<loc>${escapeXml(url)}</loc>
${hreflangTags}
${defaultHreflang}
		<changefreq>weekly</changefreq>
		<priority>0.7</priority>
		<lastmod>${formatDate(finalLastmod)}</lastmod>
	</url>`);
		}
	}

	for (const language of LANGUAGES) {
		try {
			const result = await getProjects({ language: language, includeInactive: false });
			const items = result.posts || result.items || result || [];

			for (const item of items) {
				const slug = item.slug;
				const url = `${baseUrl}/${language}/work/${escapeXml(slug)}`;
				const lastmod = formatDate(new Date());

				if (!itemGroups.has(slug)) {
					itemGroups.set(slug, []);
				}
				itemGroups.get(slug)!.push({ lang: language, url, lastmod, slug });
			}
		} catch (error) {
			console.error(`Error fetching getProjects for ${language}:`, error);
		}
	}

	// Generate URL entries with hreflang
	for (const [slug, langUrls] of itemGroups.entries()) {
		// Try to get lastmod from PageSEO for this route pattern, fallback to entity dates
		const routePattern = `/work/:slug`;
		let routeLastmod = await getRouteLastmod(routePattern);

		// If no PageSEO entry, use the latest entity date from langUrls
		if (!routeLastmod && langUrls.length > 0) {
			const entityDates = langUrls
				.map((lu) => lu.lastmod)
				.filter((d): d is string => !!d)
				.map((d) => new Date(d).getTime());
			if (entityDates.length > 0) {
				routeLastmod = new Date(Math.max(...entityDates));
			}
		}

		for (const { lang, url, lastmod } of langUrls) {
			// Use PageSEO date if available, otherwise use entity date, otherwise current date
			const finalLastmod = routeLastmod || (lastmod ? new Date(lastmod) : null) || new Date();

			const hreflangTags = langUrls
				.map(
					(lu) => `		<xhtml:link rel="alternate" hreflang="${lu.lang}" href="${escapeXml(lu.url)}" />`
				)
				.join('\n');
			const defaultHreflang = `		<xhtml:link rel="alternate" hreflang="x-default" href="${escapeXml(langUrls.find((lu) => lu.lang === 'ro')?.url || langUrls[0].url)}" />`;

			urls.push(`
	<url>
		<loc>${escapeXml(url)}</loc>
${hreflangTags}
${defaultHreflang}
		<changefreq>weekly</changefreq>
		<priority>0.7</priority>
		<lastmod>${formatDate(finalLastmod)}</lastmod>
	</url>`);
		}
	}

	return `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">${urls.join('')}
</urlset>`;
}

export const GET: RequestHandler = async ({ url }) => {
	const baseUrl = url.origin;
	const sitemapXml = await generateSitemapXml(baseUrl);

	// ISR: Cache sitemap for 1 hour (3600 seconds)
	// The sitemap will be regenerated when content changes via cache invalidation
	const isrExpiration = 3600; // 1 hour

	return new Response(sitemapXml, {
		headers: {
			'Content-Type': 'application/xml',
			'Cache-Control': 'public, max-age=3600', // Browser cache
			'x-isr-expiration': isrExpiration.toString() // ISR cache expiration
		}
	});
};
