/**
 * Standalone demo of the team invitation email layout.
 *
 * Run: `bun run scripts/demo-invitation-email.ts > /tmp/invite-demo.html && open /tmp/invite-demo.html`
 */

function escapeHtml(s: string): string {
	return s
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}

const tenantName = 'OneTop Solutions';
const inviterName = 'Augustin Constantin';
const invitationUrl = 'http://localhost:5173/invite/preview-token-abc-123';
const themeColor = '#1877F2';

function renderCtaButton(url: string, label: string, color: string): string {
	return `
		<table role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin: 16px 0 24px 0;">
			<tr>
				<td>
					<a href="${url}"
						style="display: inline-block; padding: 12px 22px; background: ${color}; color: white; text-decoration: none; border-radius: 9px; font-weight: 700; font-size: 14px; font-family: 'Inter', system-ui, sans-serif;">
						${label}
					</a>
				</td>
			</tr>
		</table>
	`;
}

const safeTenantName = escapeHtml(tenantName);
const safeInviterName = escapeHtml(inviterName);

const bodyHtml = `
	<p style="color: #111827; font-size: 15px; line-height: 1.6; margin: 0 0 12px 0;">Bună ziua,</p>
	<p style="color: #111827; font-size: 15px; line-height: 1.6; margin: 0 0 20px 0;"><strong>${safeInviterName}</strong> v-a invitat să vă alăturați echipei <strong>${safeTenantName}</strong> pe platforma CRM.</p>
	${renderCtaButton(invitationUrl, 'Acceptă invitația', themeColor)}
	<p style="color: #6b7280; font-size: 13px; line-height: 1.6; margin: 0 0 4px 0;">Sau copiați acest link în browser:</p>
	<p style="color: ${themeColor}; font-size: 13px; line-height: 1.6; margin: 0 0 20px 0; word-break: break-all;">${invitationUrl}</p>
	<p style="color: #9ca3af; font-size: 12px; line-height: 1.5; margin: 0 0 6px 0;">Această invitație expiră în 7 zile.</p>
	<p style="color: #9ca3af; font-size: 12px; line-height: 1.5; margin: 0 0 18px 0;">Dacă nu ați așteptat această invitație, puteți ignora acest email.</p>
`;

const html = `<!doctype html>
<html lang="ro">
<head>
	<meta charset="utf-8" />
	<title>Invitație — ${safeTenantName} (preview)</title>
	<style>
		body { margin: 0; padding: 24px; background: #f4f6fa; font-family: 'Inter', system-ui, sans-serif; }
		.email-card { max-width: 600px; margin: 0 auto; background: white; border-radius: 14px; overflow: hidden; box-shadow: 0 4px 12px rgba(15,23,42,.06); }
		.email-header { background: ${themeColor}; padding: 22px 28px; color: white; }
		.email-header h1 { margin: 0; font-size: 20px; font-weight: 800; letter-spacing: -.02em; }
		.email-body { padding: 28px; }
		.email-foot { padding: 14px 28px; border-top: 1px solid #e5e9f0; font-size: 11.5px; color: #94a3b8; text-align: center; }
	</style>
</head>
<body>
	<div class="email-card">
		<div class="email-header">
			<h1>Invitație nouă · ${safeTenantName}</h1>
		</div>
		<div class="email-body">${bodyHtml}</div>
		<div class="email-foot">
			OneTop Solutions CRM · invitație autogenerated · expiră în 7 zile
		</div>
	</div>
</body>
</html>`;

console.log(html);
